version: '3'
services:

  # Start Python langchain backend
  #================
  core:
    build: ./apps/core
    ports: 
      - '8000:8000'
    env_file:
      - .env 
  # End Python langchain backend
  #================


  #================
  # Start Motorbase memory server
  motorhead: 
    image: ghcr.io/getmetal/motorhead:latest
    ports:
      - '8080:8080'
    links:
      - redis
    environment:
      MOTORHEAD_PORT: 8080
      MOTORHEAD_LONG_TERM_MEMORY: 'true'
      REDIS_URL: 'redis://redis:6379'
    env_file:
      - .env
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '6379:6379'
  
  # End Motorbase memory server
  #================


  #================
  # Start Qdrant vectorstore

  index: 
    image: qdrant/qdrant
    ports:
      - '6333:6333'
