import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { supabase } from '../lib/supabaseClient'
import { useEffect, useState } from 'react'

import { Prompt } from '../components/Prompt'
import { useLatestGenerationMessage } from '@/hooks/useLatestGeneration'


const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
    let { data } = await supabase.from('generations').select()

    return {
        props: {
            generations: data
        },
    }
}

export default function Home({ generations }: any) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className="flex justify-center border border-b-neutral-300 bg-neutral-100 py-2 text-sm text-neutral-500 dark:border-none dark:bg-[#444654] dark:text-neutral-200">
            {/* {t('Model')}: {selectedConversation?.model.name} */}
            <button
            className="ml-2 cursor-pointer hover:opacity-50"
            // onClick={handleSettings}
            >
            {/* <IconSettings size={18} /> */}
            Settings
            </button>
            <button
            className="ml-2 cursor-pointer hover:opacity-50"
            // onClick={onClearAll}
            >
            {/* <IconClearAll size={18} /> */}
            Clear All
            </button>
        </div>

        {/* {selectedConversation?.messages.map((message, index) => (
            <ChatMessage
            key={index}
            message={message}
            messageIndex={index}
            />
        ))}

        {loading && <ChatLoader />} */}

        <div
            className="h-[162px] bg-white dark:bg-[#343541]"
        />

        <Prompt></Prompt>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
